version: '3.8'
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=dss
      - POSTGRES_PASSWORD=dss
      - POSTGRES_DB=eternamemoria
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
      - ./database:/docker-entrypoint-initdb.d
volumes:
  db:
    driver: local